name: ncg4
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python==3.12
  - compilers
  - cmake
  #Dev pkgs needed by Geant4Config.cmake, which would otherwise fall back to
  #older system versions or fail:
  - zlib
  - freetype
  - make
  - expat #TODO: Still needed? Maybe not after geant4 11.3.0
  - pip
