name: ncg4
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python==3.12
  - compilers
  - cmake
  #Headers+dev lib, so Geant4Config.cmake does not fall back to an older system zlib:
  - zlib
  - make
  - expat #TODO: Still needed? Maybe not after geant4 11.3.0
  - pip
